// Demand forecast viewer: pick a product, see its recent actual sales (blue)
// and the Prophet-predicted next 30 days (orange dashed), plus the model's
// accuracy (MAPE) from back-testing.
import { useEffect, useState } from 'react'
import {
  LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer,
  CartesianGrid, Legend,
} from 'recharts'
import { getJSON } from '../lib/api'

export default function Forecast() {
  const [products, setProducts] = useState([])
  const [pid, setPid] = useState(null)
  const [data, setData] = useState(null)

  useEffect(() => {
    getJSON('/api/products').then((list) => {
      setProducts(list)
      if (list.length) setPid(list[0].id)
    }).catch(() => {})
  }, [])

  useEffect(() => {
    if (pid == null) return
    setData(null)
    getJSON(`/api/forecast/${pid}`).then(setData).catch(() => {})
  }, [pid])

  // Join actual history and forecast into one series for the chart.
  const chart = data
    ? data.history.map((h) => ({ date: h.date.slice(5), actual: h.qty }))
        .concat(data.forecast.map((f) => ({
          date: f.date.slice(5), predicted: Math.round(f.yhat),
        })))
    : []

  const metric = data && data.metric
  return (
    <div className="portlet"><div className="portlet-body">
      <div className="d-flex justify-content-between align-items-center mb-2 flex-wrap gap-2">
        <h6 className="mb-0 text-rb-green">Demand forecast — next 30 days</h6>
        <div className="d-flex align-items-center gap-2">
          {metric && metric.mape != null && metric.mape < 15 && (
            <span className="badge bg-success">
              Accuracy {(100 - metric.mape).toFixed(1)}% · MAE {metric.mae}
            </span>
          )}
          {metric && metric.mae != null && (metric.mape == null || metric.mape >= 15) && (
            <span className="badge bg-light text-dark border" title="MAE is the fairer accuracy measure for low-volume products">
              Avg error ±{metric.mae} units/day{metric.mape != null && ` · MAPE ${metric.mape}%`}
            </span>
          )}
          <select className="form-select form-select-sm" style={{ width: 'auto' }}
                  value={pid ?? ''} onChange={(e) => setPid(Number(e.target.value))}>
            {products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
          </select>
        </div>
      </div>

      {!data ? <p className="text-muted mb-0">Loading forecast…</p> : (
        <ResponsiveContainer width="100%" height={260}>
          <LineChart data={chart}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="date" fontSize={10} interval={6} />
            <YAxis fontSize={11} />
            <Tooltip />
            <Legend />
            <Line type="monotone" dataKey="actual" name="Actual" stroke="#0d6efd"
                  strokeWidth={2} dot={false} />
            <Line type="monotone" dataKey="predicted" name="Forecast" stroke="#fd7e14"
                  strokeWidth={2} strokeDasharray="5 5" dot={false} />
          </LineChart>
        </ResponsiveContainer>
      )}
      <div className="form-text">
        Generated by Facebook Prophet from daily sales history. MAPE below 15% is
        considered accurate for retail demand.
      </div>
    </div></div>
  )
}
